# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Alisha Aneja
tagline:          'Welcome to my world!'
description:      'Programmer by Profession, Explorer by Heart <3'
url:              http://alisha17.github.io

author:
  name:           'Alisha Aneja'
  url:             alisha17.github.io
  email:          'anejaalisha37@gmail.com'
  github:         'https://github.com/alisha17'
  twitter:        'https://twitter.com/alisha_aneja17'
  linkedin:       'https://www.linkedin.com/in/alisha-aneja-509252128/'
  wordpress:      'https://mealisha.wordpress.blog'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/alisha17

gems:             [jekyll-gist, jekyll-paginate, jekyll-archives]
