# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks

# Setup
title:            Alisha Aneja
tagline:          'Welcome'
<<<<<<< HEAD
description:      'Programmer by Profession'
=======
description:      ' Programmer by Profession'
>>>>>>> f41f8bc91b9af3b26678c401d007c8b2a79323fc
url:              http://alisha17.github.io

author:
  name:           'Alisha Aneja'
  url:             alisha17.github.io
  email:          'anejaalisha37@gmail.com'
  github:         'https://github.com/alisha17'
  twitter:        'https://twitter.com/alisha_aneja17'
  linkedin:       'https://www.linkedin.com/in/alisha-aneja-509252128/'
  wordpress:      'https://mealisha.wordpress.com/'
  rss:            'https://alisha17.github.io/feed.xml'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/alisha17

gems:             [jekyll-gist, jekyll-paginate, jekyll-archives]

defaults:
  - scope:
      path: "assets"
    values:
      image: true

plugins:
  - jekyll-feed
  